<a href="https://colab.research.google.com/github/anttox/C8280/blob/main/Actividad2/TareaNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy

NumPy es la librería central para computación científica en Python. Proporciona un objeto de matriz multidimensional de alto rendimiento y herramientas para trabajar con estas matrices.

#### Matrices

Una matriz NumPy es una colección de valores de tipos de datos similares y está indexada por una tupla de números no negativos. El rango de la matriz es el número de dimensiones, y la forma de una matriz es una tupla de números que dan el tamaño de la matriz a lo largo de cada dimensión.


In [ ]:
# Ejemplo
from __future__ import division
import time
import numpy as np


tam_vec = 1000
def lista_python():
    t1 = time.time()
    X = range(tam_vec)
    Y = range(tam_vec)
    Z = []
    for i in range(len(X)):
        Z.append(X[i] + Y[i])
    return time.time() - t1

def matriz_numpy():
    t1 = time.time()
    X = np.arange(tam_vec)
    Y = np.arange(tam_vec)
    Z = X + Y
    return time.time() - t1

time1 = lista_python()
time2 = matriz_numpy()

print("Tiempo usando lista de Python:", time1)
print("Tiempo usando matriz NumPy:", time2)

Tiempo usando lista de Python: 0.0003364086151123047
Tiempo usando matriz NumPy: 0.0055773258209228516


In [ ]:
#import numpy
#numpy.__version__

import numpy as np

print("Version de Numpy:", np.__version__)

Version de Numpy: 1.22.4


Podemos inicializar matrices NumPy a partir de listas de Python anidadas y acceder a los elementos mediante corchetes.

In [ ]:
import numpy as np

# Creamos una matriz de rango 1
a = np.array([0, 1, 2])
print (type(a))

# Imprimimos la dimension de la matriz
print (a.shape)
print (a[0])
print (a[1])
print (a[2])

# Cambiamos un elemento de un array
a[0] = 5
print (a)

<class 'numpy.ndarray'>
(3,)
0
1
2
[5 1 2]


In [ ]:
# Creamos una matriz de rango 2
b = np.array([[0,1,2],[3,4,5]])
print (b.shape)
print (b)
print (b[0, 0], b[0, 1], b[1, 0])

(2, 3)
[[0 1 2]
 [3 4 5]]
0 1 3


In [ ]:
print ( b.shape)
print ( b[0, 0], b[0, 1], b[1, 0])

(2, 3)
0 1 3


### Creación de una matriz NumPy

NumPy también proporciona muchas funciones integradas para crear matrices. La mejor manera de aprender esto es a través de ejemplos, así que pasemos al código.

In [ ]:
# Creamos una matriz 3x3 de todos ceros
a = np.zeros((3,3))
print (a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# Creamos una matriz 2x2 de todos 1
b = np.ones((2,2))
print (b)

[[1. 1.]
 [1. 1.]]


In [ ]:
# Creamos una matriz 3x3 constantes
c = np.full((3,3), 7)
print(c)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
# Creamos una matriz 3x3 con valores aleatorios
d = np.random.random((3,3))
print (d)

[[0.51856572 0.7364212  0.95619108]
 [0.93745927 0.50859868 0.35878842]
 [0.61814495 0.21056075 0.11678428]]


In [ ]:
# Creamos una matriz identidad 3x3
e = np.eye(3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Convertir una lista en una matriz
f = np.array([2, 3, 1,0])
print(f)

[2 3 1 0]


In [ ]:
# arange() crea matrices con valores que se incrementan regularmente
g = np.arange(1,11,1)
print(g)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# Mezcla de tupla y listas

# Creamos una tupla y una lista
tupla = (1, 2, 3)
lista = [4, 5, 6]

# Convertimos la tupla en un arreglo de NumPy
tupla_np = np.array(tupla)

# Concatenar la lista y el arreglo de la tupla
h = np.concatenate((lista, tupla_np))

print(h)

[4 5 6 1 2 3]


In [ ]:
# Crear una matriz de rango con tipo de datos flotante
i = np.arange(1, 8, dtype=np.float64)
print(i)

[1. 2. 3. 4. 5. 6. 7.]


`linspace()`  crea matrices con un numero especifico de elementos que están espaciados por igual entre los valores inicial y final especificados

In [ ]:
# Creamos una matriz con 5 elementos espaciados entre 1 y 10
j = np.linspace(1, 10, 5)

# Imprimir la matriz
print(j)

[ 1.    3.25  5.5   7.75 10.  ]


### Tipos de datos
Una matriz es una colección de elementos del mismo tipo de datos y NumPy admite y proporciona funciones integradas para construir matrices con argumentos opcionales para especificar explícitamente los tipos de datos requeridos.

In [ ]:
# Numpy escoge el tipo de datos
x = np.array([0, 1])
y = np.array([2.0, 3.0])

# Fuerza un tipo de datos en particular
z = np.array([5, 6], dtype=np.int64)
print (x.dtype, y.dtype, z.dtype)

int64 float64 int64


**Ejercicio** Completa el siguiente  código.

In [ ]:
#np.random.seed(0)

x1 = np.random.randint(10, size=6)  # matriz 1-d
x2 = np.random.randint(10, size=(5, 4))  # matriz-2d
x3 = np.random.randint(10, size=(2, 4, 5)) # matriz-3d

# Imprime los atributos : dim, shape, size, dtype, itemsize y nbytes

# Imprimir atributos de x1
print("Atributos de x1:")
print("Dimensión (dim):", x1.ndim)
print("Forma (shape):", x1.shape)
print("Tamaño (size):", x1.size)
print("Tipo de datos (dtype):", x1.dtype)
print("Tamaño del elemento (itemsize):", x1.itemsize)
print("Tamaño total en bytes (nbytes):", x1.nbytes)
print()

# Imprimir atributos de x2
print("Atributos de x2:")
print("Dimensión (dim):", x2.ndim)
print("Forma (shape):", x2.shape)
print("Tamaño (size):", x2.size)
print("Tipo de datos (dtype):", x2.dtype)
print("Tamaño del elemento (itemsize):", x2.itemsize)
print("Tamaño total en bytes (nbytes):", x2.nbytes)
print()

# Imprimir atributos de x3
print("Atributos de x3:")
print("Dimensión (dim):", x3.ndim)
print("Forma (shape):", x3.shape)
print("Tamaño (size):", x3.size)
print("Tipo de datos (dtype):", x3.dtype)
print("Tamaño del elemento (itemsize):", x3.itemsize)
print("Tamaño total en bytes (nbytes):", x3.nbytes)

Atributos de x1:
Dimensión (dim): 1
Forma (shape): (6,)
Tamaño (size): 6
Tipo de datos (dtype): int64
Tamaño del elemento (itemsize): 8
Tamaño total en bytes (nbytes): 48

Atributos de x2:
Dimensión (dim): 2
Forma (shape): (5, 4)
Tamaño (size): 20
Tipo de datos (dtype): int64
Tamaño del elemento (itemsize): 8
Tamaño total en bytes (nbytes): 160

Atributos de x3:
Dimensión (dim): 3
Forma (shape): (2, 4, 5)
Tamaño (size): 40
Tipo de datos (dtype): int64
Tamaño del elemento (itemsize): 8
Tamaño total en bytes (nbytes): 320


Del ejercicio anterior hay una manera de reducir el codigo usando FOR

In [ ]:
np.random.seed(0)

matrices = [np.random.randint(10, size=6), np.random.randint(10, size=(5, 4)), np.random.randint(10, size=(2, 4, 5))]

#Usamos enumerate() para iterar obre las matrices y mostrar sus tributos
for i, matriz in enumerate(matrices):
    print(f"Atributos de x{i+1}:")
    print("Dimensión (dim):", matriz.ndim)
    print("Forma (shape):", matriz.shape)
    print("Tamaño (size):", matriz.size)
    print("Tipo de datos (dtype):", matriz.dtype)
    print("Tamaño del elemento (itemsize):", matriz.itemsize)
    print("Tamaño total en bytes (nbytes):", matriz.nbytes)
    print()

Atributos de x1:
Dimensión (dim): 1
Forma (shape): (6,)
Tamaño (size): 6
Tipo de datos (dtype): int64
Tamaño del elemento (itemsize): 8
Tamaño total en bytes (nbytes): 48

Atributos de x2:
Dimensión (dim): 2
Forma (shape): (5, 4)
Tamaño (size): 20
Tipo de datos (dtype): int64
Tamaño del elemento (itemsize): 8
Tamaño total en bytes (nbytes): 160

Atributos de x3:
Dimensión (dim): 3
Forma (shape): (2, 4, 5)
Tamaño (size): 40
Tipo de datos (dtype): int64
Tamaño del elemento (itemsize): 8
Tamaño total en bytes (nbytes): 320



### Indexación de matrices

NumPy ofrece varias formas de indexar en matrices. La sintaxis estándar de Python `x[obj]` se puede usar para indexar la matriz NumPy, donde `x` es la matriz y `obj` es la selección.

Hay tres tipos de indexación disponibles:

* Acceso al campo

* Recorte básico

* Indexación avanzada

#### Acceso al campo

Si el objeto ndarray es una matriz estructurada, se puede acceder a los campos de la matriz indexando la matriz con cadenas, como un diccionario. La indexación de `x['field-name']` devuelve una nueva vista de la matriz, que tiene la misma dimensión que `x`, excepto cuando el campo es una submatriz  que contiene sólo la parte de los datos en el campo especificado. Los tipos de datos se obtienen con `x.dtype['field-name']`.

In [ ]:
x = np.zeros((3,3), dtype=[('a', np.int32), ('b', np.float64, (3,3))])
print(x)

[[(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
  (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
  (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])]
 [(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
  (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
  (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])]
 [(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
  (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
  (0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])]]


In [ ]:
print ("x['a'].shape: ",x['a'].shape)
print ("x['a'].dtype: ", x['a'].dtype)

print ("x['b'].shape: ", x['b'].shape)
print ("x['b'].dtype: ", x['b'].dtype)

x['a'].shape:  (3, 3)
x['a'].dtype:  int32
x['b'].shape:  (3, 3, 3, 3)
x['b'].dtype:  float64


#### Recorte básico

Las matrices NumPy se pueden dividir, de forma similar a las listas. Debe especificar un segmento para cada dimensión de la matriz, ya que las matrices pueden ser multidimensionales.

La sintaxis de división básica es `i: j: k`, donde `i` es el índice inicial, `j` es el índice final, `k` es el paso y `k` no es igual a 0. Esto selecciona los elementos `m` en la dimensión correspondiente, con valores de índice `, i + k, ...,i + (m - 1)k` donde `m = q + (r distinto de 0)`,  `q` y `r` son el cociente y el resto se obtiene dividiendo `j - i` entre `k`: `j - i = qk + r`, de modo que `i + (m - 1) k < j`.

In [ ]:
x = np.array([5, 6, 7, 8, 9])
x[1:7:2]

array([6, 8])

La `k` negativa hace que los pasos vayan hacia índices más pequeños. Los `i` y `j` negativos se interpretan como `n + i` y `n + j` donde `n` es el número de elementos en la dimensión correspondiente.

In [ ]:
print (x[-2:5])
print (x[-1:1:-1])

[8 9]
[9 8 7]


Si `n` es el número de elementos en la dimensión que se está recortando. Entonces, si no se proporciona `i`, el valor predeterminado es `0` para  `k > 0` y `n-1` para `k < 0`. Si no se proporciona `j`, el valor predeterminado es `n` para `k > 0` y `-1` para `k < 0`. Si no se proporciona `k`, el valor predeterminado es `1`. Ten en cuenta que `::` es lo mismo que `:` y significa seleccionar todos los índices a lo largo de este eje.

In [ ]:
x[4:]

array([9])

Si el número de objetos en la tupla de selección es menor que N , entonces se asume `:` para cualquier dimensión subsiguiente.

In [ ]:
x[1:4]

array([6, 7, 8])

Los puntos suspensivos se expanden al número de : objetos necesarios para hacer una tupla de selección de la misma longitud que `x.ndim`. Solo puede haber una sola elipsis presente.

In [ ]:
print(x)

[5 6 7 8 9]


In [ ]:
x[...,0]

array(5)

#### Ejercicio

1. Crea una matriz de rango `2` con dimension `(3, 4)`

2. Usa el recorte para extraer la submatriz que consta de las primeras `2` filas y las columnas `1` y `2`.

3. Una parte de una matriz es solo una vista de los mismos datos, comprueba quecualquier modificación modificará la matriz original.



In [ ]:
# Tu respuesta
# Creamos una matriz de rango 2 con dimensiones (3, 4)
matriz = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

# Extraemos la submatriz de las primeras 2 filas y las columnas 1 y 2
submatriz = matriz[:2, 1:3]

print("Matriz original:")
print(matriz)
print()

print("Submatriz extraída:")
print(submatriz)
print()

# Modificamos un elemento de la submatriz
submatriz[0, 0] = 99

print("Matriz original después de modificar la submatriz:")
print(matriz)
print()

Matriz original:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Submatriz extraída:
[[2 3]
 [6 7]]

Matriz original después de modificar la submatriz:
[[ 1 99  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]



Se puede acceder a la matriz de la fila central de dos maneras.

* Las partes junto con la indexación de enteros darán como resultado una matriz de rango inferior.

* El uso de solo recortes dará como resultado el mismo rango matriz.

In [ ]:
# Creamos una matriz de rango 2 array con dimensión (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print (a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Dos formas de acceder a los datos en la fila central de la matriz. La combinación de la indexación de enteros con recortes produce una matriz de menor rango, mientras que el uso de solo recortes produce una matriz del mismo rango que la matriz original:

In [ ]:
fila_r1 = a[1, :]    # Vista de rango 1 de la segunda fila de a
fila_r2 = a[1:2, :]  # Vista de rango 2 de la segunda fila de a
fila_r3 = a[[1], :]  # Vista de ranfo 2 de la segunda fila de a
print (fila_r1, fila_r1.shape)
print (fila_r2, fila_r2.shape)
print (fila_r3, fila_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


Podemos hacer la misma distinción al acceder a las columnas de una matriz.

In [ ]:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print (col_r1, col_r1.shape)
print (col_r2, col_r2.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


### Indexación avanzada


In [ ]:
a = np.array([[1,2], [3, 4]])
print (a[[0, 1], [0, 1]])

# El ejemplo de indexacion de una matriz entera es equivalente a esto:
# Indexar una matriz entera
indices = np.ix_([0, 1], [0, 1])
resultado = a[indices]

print("Resultado:")
print(resultado)

[1 4]
Resultado:
[[1 2]
 [3 4]]


Al usar la indexacion de un matriz de enteros, puede reutilizar el mismo elemento de la matriz de origen:

In [ ]:
print (a[[0, 0], [1, 1]])

# Equivalente al ejemplo de indexacion de matriz de enteros
# Indexar una matriz de enteros
indices = np.array([[0, 0], [1, 1]])
resultado = a[indices[0], indices[1]]

print("Resultado:")
print(resultado)

[2 2]
Resultado:
[2 2]


Un asunto  importante y extremadamente útil acerca de los recortes de una  matriz es que devuelven  *vistas (`views`)* en lugar de *copias (`copies`)*  de los datos de la matriz. Este es un área en la que NumPy  difiere de la lista de Python:  en las listas, estas son copias.

In [ ]:
np.random.seed(0)
x2 = np.random.randint(10, size=(5, 4))
x2

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6],
       [8, 8, 1, 6],
       [7, 7, 8, 1]])

In [ ]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[5 0]
 [7 9]]


In [ ]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  0]
 [ 7  9]]


Este comportamiento predeterminado es realmente muy útil: significa que cuando trabajamos con grandes conjuntos de datos, podemos acceder y procesar partes de estos conjuntos de datos sin necesidad de copiar el búfer de datos.

A pesar de las características  de las `vistas` de una  matriz, a veces es útil copiar de forma explícita los datos dentro de una matriz o una submatriz. Esto se puede hacer  con el método `copy()`:

In [ ]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  0]
 [ 7  9]]


In [ ]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  0]
 [ 7  9]]


In [ ]:
print(x2)

[[99  0  3  3]
 [ 7  9  3  5]
 [ 2  4  7  6]
 [ 8  8  1  6]
 [ 7  7  8  1]]


### Reshaping

In [ ]:
x4 = np.arange(1, 10).reshape((3, 3))
print(x4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Ten en cuenta que para que esto funcione, el tamaño de la matriz inicial debe coincidir con el tamaño de la matriz rediseñada. Siempre que sea posible, el método `reshape` utilizará una `vista` sin copia de la matriz inicial.

Otro patrón de `reshaping `, es la conversión de una matriz unidimensional en una fila o columna de una matriz bidimensional. Esto se puede hacer con el método `reshape`  o más fácilmente haciendo uso de `newaxis` dentro de una operación de división:

In [ ]:
x5 = np.array([1, 2, 3])
x5

array([1, 2, 3])

In [ ]:
# vector fila via reshape
# Convertimos el arreglo en un vector fila utilizando reshape
a = x5.reshape((1, -1))

print("Vector fila:")
print(a)

Vector fila:
[[1 2 3]]


In [ ]:
# vector fila con newaxis
# Convertimos el arreglo en un vector fila utilizando np.newaxis
b = x5[np.newaxis, :]

print("Vector fila:")
print(b)

Vector fila:
[[1 2 3]]


In [ ]:
# vector columna via reshape
# Convertimos el arreglo en un vector columna utilizando reshape
c = x5.reshape((-1, 1))

print("Vector columna:")
print(c)

Vector columna:
[[1]
 [2]
 [3]]


In [ ]:
# vector columna con newaxis
# Convertir el arreglo en un vector columna utilizando np.newaxis
d = x5[:, np.newaxis]

print("Vector columna:")
print(d)

Vector columna:
[[1]
 [2]
 [3]]


### Concatenación y  separación


In [ ]:
x = np.array([4, 5, 6])
y = np.array([7, 8, 9])
np.concatenate([x, y])

array([4, 5, 6, 7, 8, 9])

In [ ]:
# concatenacion de dos o mas matrices
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 4  5  6  7  8  9 99 99 99]


In [ ]:
# concatendo una matriz dos veces
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

Para trabajar con matrices de distintas dimensiones, se usan las funciones `vstack` y `hstack`:

In [ ]:
x = np.array([0, 1, 2])
grid = np.array([[3, 4, 5],
                 [6, 5, 4]])

# Se junta la matriz de manera vertical
# Unimos la matriz y el arreglo de manera vertical
aiter = np.vstack((x, grid))

print("Resultado:")
print(a)

Resultado:
[[1 2 3]]


In [ ]:
# Se junta la matriz de manera horizontal
y = np.array([[23],
              [23]])
# Unimos la matriz y la matriz de manera horizontal
b = np.hstack((grid, y))

print("Resultado:")
print(b)

Resultado:
[[ 3  4  5 23]
 [ 6  5  4 23]]


Lo contrario de la concatenación es la división o separación, que es implementado por las funciones `np.split`, `np.hsplit` y `np.vsplit`. Para cada uno de estas funciones , podemos pasar una lista de índices que dan los puntos de división.

Ver:[https://numpy.org/doc/stable/reference/generated/numpy.split.html](https://numpy.org/doc/stable/reference/generated/numpy.split.html)

In [ ]:
x = [1, 2, 3, 44, 95, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [44 95] [3 2 1]


In [ ]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
grid1, grid2 = np.vsplit(grid, [2])
print(grid1)
print(grid2)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
grid3, grid4 = np.hsplit(grid,[2])
print(grid3)
print(grid4)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


### Fancy


In [ ]:
rand = np.random.RandomState(42)
x = rand.randint(100, size=10)
print(x)

[51 92 14 71 60 20 82 86 74 74]


In [ ]:
# Accedemos a tres elementos diferentes
[x[1], x[5], x[2]]

[92, 20, 14]

Alternativamente, podemos pasar una sola lista o matriz de índices para obtener el mismo resultado:

In [ ]:
rand = np.random.RandomState(42)
x = rand.randint(100, size=10)
indices = [0, 2, 4]
# Seleccionar elementos utilizando una lista de índices
resultado = x[indices]

print("Resultado:")
print(resultado)

Resultado:
[51 14 60]


Cuando se utiliza fancy, la forma del resultado refleja la forma de las matrices de índice en lugar de la forma de la matriz que se indexa y trabaja  en múltiples  dimensiones:

In [ ]:
rand = np.random.RandomState(42)

x = np.arange(12).reshape((3, 4))

indices_filas = rand.randint(0, arr.shape[0], size=2)
indices_columnas = rand.randint(0, arr.shape[1], size=2)

# Seleccionamos los elementos utilizando indexación avanzada con matrices de índices
resultado = x[indices_filas, indices_columnas]

print("Resultado:")
print(resultado)
print("Forma del resultado:", resultado.shape)

Resultado:
[10  2]
Forma del resultado: (2,)


In [ ]:
X = np.arange(12).reshape((3, 4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Al igual que con la indexación estándar, el primer índice se refiere a la fila, y el segundo a la columna:

In [ ]:
fila = np.array([0, 1, 2])
col = np.array([2, 1, 3])
X[fila, col]

array([ 2,  5, 11])

Observa que el primer valor en el resultado es `X[0, 2]`, el segundo es `X[1, 1]`  y el tercero es `X[2, 3]`. El emparejamiento de índices en la indexación fancy  sigue todas las reglas del broadcasting, por ejemplo, si combinamos un vector de columna y un vector de fila dentro de los índices, obtenemos un resultado bidimensional:

In [ ]:
x = np.arange(24).reshape((6, 4))

fila = np.array([0, 1, 2])
col = np.array([2, 1, 3])

# Seleccionamos los elementos utilizando indexación avanzada con matrices de índices
resultado = x[fila, col]

print("Resultado:")
print(resultado)
print("Forma del resultado:", resultado.shape)

Resultado:
[ 2  5 11]
Forma del resultado: (3,)


Aquí, cada valor de fila se empareja con cada vector de columna, exactamente como se hace en broadcasting  de operaciones aritméticas. Por ejemplo:

In [ ]:
# Completar
# Suma entre un array 1D y un escalar
a = np.array([1, 2, 3])
b = 2
resultado = a + b
print("Resultado de la suma:")
print(resultado)

# Suma entre un array 2D y un vector columna
c = np.array([[1, 2, 3],
              [4, 5, 6]])
d = np.array([[10],
              [20]])
resultado = c + d
print("Resultado de la suma:")
print(resultado)

# Producto entre un array 2D y un escalar
e = np.array([[1, 2, 3],
              [4, 5, 6]])
f = 2
resultado = e * f
print("Resultado del producto:")
print(resultado)

# Producto entre un array 3D y un vector fila
g = np.array([[[1, 2],
               [3, 4]],
              [[5, 6],
               [7, 8]]])
h = np.array([10, 20])
resultado = g * h[:, np.newaxis]
print("Resultado del producto:")
print(resultado)

Resultado de la suma:
[3 4 5]
Resultado de la suma:
[[11 12 13]
 [24 25 26]]
Resultado del producto:
[[ 2  4  6]
 [ 8 10 12]]
Resultado del producto:
[[[ 10  20]
  [ 60  80]]

 [[ 50  60]
  [140 160]]]


Siempre es importante recordar que en  la indexación fancy, el valor de retorno refleja la forma del broadcasting  de los índices, en lugar de la forma de la matriz que se indexa.

Para operaciones  más potentes, la indexación adornada se puede combinar con los otros esquemas de indexación que existen:

In [ ]:
print(X)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# Combinando el indexado fancy y indices simples
arr = np.array([[0, 1, 2, 3],
                [4, 5, 6, 7],
                [8, 9, 10, 11]])

filas = np.array([0, 2])  # Seleccionamos las filas 0 y 2
columna = 1  # Seleccionamos la columna 1

resultado = arr[filas,columna]
print("Resultado de la combinación de indexación fancy e índice simple:")
print(resultado)

Resultado de la combinación de indexación fancy e índice simple:
[1 9]


In [ ]:
# Combinando el indexado fancy y el recorte
arr = np.array([[0, 1, 2, 3],
                [4, 5, 6, 7],
                [8, 9, 10, 11]])

indices_filas = np.array([0, 2])  # Seleccionamos las filas 0 y 2
recorte_columnas = slice(1, 3)  # Seleccionamos las columnas 1 y 2

resultado = arr[indices_filas, recorte_columnas]
print("Resultado de la combinación de indexación fancy y recorte:")
print(resultado)

Resultado de la combinación de indexación fancy y recorte:
[[ 1  2]
 [ 9 10]]


Así como el fancy  se puede utilizar para acceder a partes de una matriz, también se puede utilizar para modificar partes de una matriz. Por ejemplo, si  tenemos una matriz de índices y nos gustaría establecer los elementos correspondientes en una matriz a algún valor, podemos hacer lo siguiente:

In [ ]:
x = np.arange(10)
i = np.array([2, 1, 8, 4])
x[i] = 99
print(x)

[ 0 99 99  3 99  5  6  7 99  9]


Los índices repetidos con estas operaciones pueden causar algunos resultados potencialmente inesperados. Considera lo siguiente:

In [ ]:
x = np.zeros(10)
x[[0, 0]] = [4, 6]
print(x)

[6. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


El resultado de esta operación es asignar primero  `x[0] = 4`, seguido por `x[0] = 6`. Pero el resultado es que `x[0]` contiene el valor 6.

Considera la siguiente operación:

In [ ]:
i = [2, 3, 3, 4, 4, 4]
x[i] += 1
x

array([6., 0., 1., 1., 1., 0., 0., 0., 0., 0.])

En este caso algún resultado inesperado se debe conceptualmente  a que `x[i] +=1` se entiende como una abreviatura de `x[i] = x [i] + 1`. Cuando `x[i] + 1` es evaluado el resultado es asignado  a los índices en `x` . Con esto en mente, no es que el aumento que ocurre varias veces, sino la asignación, que conduce a los resultados  no intuitivos.

Si quieremos  el otro comportamiento donde se repite la operación, se puede utilizar el método `at()` de `ufuncs`:

In [ ]:
x[i] += 1
i = [2, 3, 3, 4, 4, 4]

# Operación repetida utilizando at()
np.add.at(x, i, 1)  # Suma 1 a los elementos seleccionados

print("Resultado de la operación repetida utilizando at():")
print(x)

Resultado de la operación repetida utilizando at():
[6. 0. 5. 7. 9. 0. 0. 0. 0. 0.]


El método `at()` realiza una aplicación  del operador dado en los índices especificados (aquí, `i`) con el valor especificado (aquí, `1`).

###  Expresiones vectorizadas

### Agregaciones


In [ ]:
L = np.random.random(100)
sum(L)

47.44472811197369

La sintaxis es bastante similar a la función de `sum` de  `NumPy`  y el resultado es el mismo en el caso más simple:

In [ ]:
np.sum(L)

47.4447281119737

Sin embargo, debido a que la operación se ejecuta  en código compilado, la versión `NumPy` de la operación se calcula mucho más rápidamente:

In [ ]:
matriz_grande = np.random.rand(1000000)
%timeit sum(matriz_grande)
%timeit np.sum(matriz_grande)

85.7 ms ± 1.25 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
360 µs ± 7.13 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


La función `sum` y la función `np.sum` no son idénticas, lo que a veces puede conducir a la confusión.  En particular, sus argumentos opcionales tienen significados diferentes  y `np.sum` es válido a  varias dimensiones de una matriz.

In [ ]:
# Otras funciones min y max
min(matriz_grande), max(matriz_grande)

(7.071203171893359e-07, 0.9999997207656334)

In [ ]:
%timeit min(matriz_grande)
%timeit np.min(matriz_grande)

61.6 ms ± 1.01 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
429 µs ± 17.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Todas estas funciones también están disponibles como métodos en la clase `ndarray`. Por ejemplo, `np.mean(data)` y `data.mean()` en el ejemplo siguiente son equivalentes:

In [ ]:
data = np.random.normal(size=(15, 15))
np.mean(data)

0.1014614979396541

In [ ]:
data.mean()

0.1014614979396541

Un tipo común de operación de agregación es un agregado a lo largo de una fila o columna.

In [ ]:
M = np.random.random((5, 6))
print(M)

[[0.1876222  0.95137218 0.44469986 0.47577551 0.43077223 0.49532871]
 [0.58341548 0.27654054 0.96025749 0.12685672 0.38686572 0.29660634]
 [0.99907694 0.00377931 0.82984241 0.75816216 0.01685189 0.23811077]
 [0.28054238 0.63922302 0.31781681 0.93091841 0.51938547 0.77906154]
 [0.4460392  0.93142267 0.00176855 0.90189974 0.47317235 0.28021716]]


De forma predeterminada, cada función de agregación de  `NumPy`  devolverá el agregado sobre toda la matriz:

In [ ]:
M.sum()

14.963403762355242

Las funciones de agregación toman un argumento adicional que especifica el eje a lo largo del cual se calcula el agregado. Por ejemplo, podemos encontrar el valor de la suma y el  mínimo de cada columna especificando `axis = 0`:

In [ ]:
M.sum(axis= 0)

array([2.4966962 , 2.80233772, 2.55438512, 3.19361254, 1.82704766,
       2.08932452])

In [ ]:
data = np.random.normal(size=(5, 10, 15))
data.sum(axis=0).shape

(10, 15)

In [ ]:
data.sum(axis=(0, 2)).shape

(10,)

In [ ]:
data.sum()

-70.65297874557393

Algunas funciones de agregación en `Numpy ` son :


|Nombre de funcion  | VersionNaN-safe     | Descripcion                                   |
|-------------------|---------------------|-----------------------------------------------|
| ``np.sum``        | ``np.nansum``       | Calcula suma de elementos                     |
| ``np.prod``       | ``np.nanprod``      | Calcula el producto de elementos              |
| ``np.mean``       | ``np.nanmean``      | Calcula la media de elementos                 |
| ``np.std``        | ``np.nanstd``       | Calcula la desviacion estandar                |
| ``np.var``        | ``np.nanvar``       | Calcula la  varianza                          |
| ``np.min``        | ``np.nanmin``       | Encuentra el minimo valor                     |
| ``np.max``        | ``np.nanmax``       | Encuentra el maximo valor                     |
| ``np.argmin``     | ``np.nanargmin``    | Encuenta el index del minimo valor            |
| ``np.argmax``     | ``np.nanargmax``    | Encuentra el index del maximo valor           |
| ``np.median``     | ``np.nanmedian``    | Calcula la mediana de elementos               |
| ``np.percentile`` | ``np.nanpercentile``| Calcula el rango estatistico de elementos     |
| ``np.any``        | N/A                 | Evalua si algun elemento es true              |
| ``np.all``        | N/A                 | Evalua si todos los elementos son true        |



#### Broadcasting


In [ ]:
a = np.array([0, 1, 2])
b = np.array([2, 6, 1])
a + b

array([2, 7, 3])

El  `broadcasting` permite que estos tipos de operaciones binarias se realicen en matrices de diferentes tamaños; por ejemplo, podemos añadir  un escalar (una matriz de dimensión cero) a una matriz:

In [ ]:
a + 5


array([5, 6, 7])

Podemos extender de manera similar esto a matrices de mayor dimensión. Veamos el resultado cuando agregamos una matriz unidimensional a una matriz bidimensional:

In [ ]:
A = np.arange(16).reshape(4, 4)
b = np.arange(4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
A + b

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14],
       [12, 14, 16, 18]])

Podemos aplicar el  `broadcasting` en dos matrices. Considere el siguiente ejemplo:

In [ ]:
# Suma entre un array 1D y un escalar
a = np.array([1, 2, 3])
b = 2
resultado = a + b
print("Resultado de la suma:")
print(resultado)


Resultado de la suma:
[3 4 5]


In [ ]:
# Suma entre un array 2D y un vector columna
c = np.array([[1, 2, 3],
              [4, 5, 6]])
d = np.array([[10],
              [20]])
resultado = c + d
print("Resultado de la suma:")
print(resultado)

Resultado de la suma:
[[11 12 13]
 [24 25 26]]


In [ ]:
# Producto entre un array 2D y un escalar
e = np.array([[1, 2, 3],
              [4, 5, 6]])
f = 2
resultado = e * f
print("Resultado del producto:")
print(resultado)

Resultado del producto:
[[ 2  4  6]
 [ 8 10 12]]


In [ ]:
# Producto entre un array 3D y un vector fila
g = np.array([[[1, 2],
               [3, 4]],
              [[5, 6],
               [7, 8]]])
h = np.array([10, 20])
resultado = g * h[:, np.newaxis]
print("Resultado del producto:")
print(resultado)

Resultado del producto:
[[[ 10  20]
  [ 60  80]]

 [[ 50  60]
  [140 160]]]


###  Regla del broadcasting

El `broadcasting` en `NumPy` sigue un estricto conjunto de reglas para determinar la interacción entre dos matrices :

* Regla 1: Si las dos matrices difieren en su número de dimensiones, la forma de la matriz que tiene menos dimensiones se rellena con unos en el lado principal (izquierdo).

* Regla 2: Si la forma de los dos matrices no coincide con ninguna dimensión, la matriz con la forma igual a 1 en esa dimensión se estira para que coincida con la otra dimensión.

* Regla 3: Si en cualquier dimensión los tamaños son distintos y ninguno es igual a 1, se genera un error.

### Un útil truco:

In [ ]:
J = np.arange(0, 40, 10)
J.shape

(4,)

In [ ]:
J = J[:, np.newaxis]  # agregamos un nuevo eje ->  matriz 2D
J.shape

(4, 1)

In [ ]:
J

array([[ 0],
       [10],
       [20],
       [30]])

In [ ]:
J + 3

array([[ 3],
       [13],
       [23],
       [33]])

### Comparaciones, máscaras y lógica Booleana


In [ ]:
a1 = np.array([1, 2, 3, 4])
b1 = np.array([4, 3, 2, 1])
a1 < b1

array([ True,  True, False, False])

In [ ]:
np.all(a1 < b1)

False

In [ ]:
np.any(a1 < b1)

True

In [ ]:
if np.all(a1 < b1):
    print(" Todos los elementos en a1 son menores que los elementos en b1 ")
elif np.any(a1 < b1):
    print("Algunos elementos en a1 son menores que los elementos de b1")
else:
    print("Todos los elementos en b1 son menores que los elementos de a1")

Algunos elementos en a1 son menores que los elementos de b1


Al aparecer en una expresión aritmética junto con un número escalar, u otra matriz `NumPy` con un tipo de datos numéricos, una matriz booleana se convierte en una matriz numérica con valores `0` y `1` en lugar de `False` y `True`, respectivamente.

In [ ]:
# Matriz booleana
matriz_bool = np.array([[True, False],
                        [False, True]])

In [ ]:
# Matriz numérica
matriz_num = np.array([[1, 2],
                       [3, 4]])

In [ ]:
# Operación de suma entre la matriz booleana y la matriz numérica
resultado = matriz_bool + matriz_num

print("Resultado de la operación de suma:")
print(resultado)

Resultado de la operación de suma:
[[2 2]
 [3 5]]


Esta es una propiedad útil para la computación condicional, como cuando se definen funciones.

In [ ]:
def pulso(t, posicion, altura, ancho):
    return altura * (t >= posicion) * (t <= (posicion + ancho))
# Asiganmos parámetros del pulso
posicion = 2
altura = 1.5
ancho = 3

# Asignamos alores de tiempo
t = np.linspace(0, 6, 100)

# GeneraMOS UN pulso
pulso_generado = pulso(t, posicion, altura, ancho)

print(pulso_generado)

[0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.5 1.5 1.5
 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5
 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5
 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 0.  0.  0.  0.  0.  0.  0.
 0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]


### Matrices booleanas como máscaras

Revisar: [masked array](https://docs.scipy.org/doc/numpy/reference/maskedarray.html).

In [ ]:
k = np.array([1, 3, -1, 5, 7, -1])
mask = (k < 0)
mask

array([False, False,  True, False, False,  True])

In [ ]:
# Un ejemplo bidimensional
rng = np.random.RandomState(0)
z1 = rng.randint(10, size=(3, 4))
z1

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [ ]:
# Un ejemplo tridimensional de tamaño (2, 3, 4)
rng = np.random.RandomState(0)
z2 = rng.randint(10, size=(2, 3, 4))
print(z2)

[[[5 0 3 3]
  [7 9 3 5]
  [2 4 7 6]]

 [[8 8 1 6]
  [7 7 8 1]
  [5 9 8 9]]]


Ahora, para seleccionar estos valores de la matriz, podemos simplemente indexar en esta matriz booleana, esto se conoce como una operación de `enmascaramiento`:

In [ ]:
z2 = np.array([[[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]],

               [[13, 14, 15, 16],
                [17, 18, 19, 20],
                [21, 22, 23, 24]]])

mask = np.array([[[True, False, False, True],
                  [False, True, True, False],
                  [True, False, True, False]],

                 [[False, True, False, False],
                  [False, False, True, True],
                  [True, False, False, True]]])

# Utilizamos el enmascaramiento para seleccionar elementos de z2
result = z2[mask]

print(result)

[ 1  4  6  7  9 11 14 19 20 21 24]


El siguiente ejemplo muestra cómo sumar la matriz de enmascaramiento,  donde `True` representa uno y `False` representa 0.

In [ ]:
mask = np.array([[True, False, True],
                 [False, True, False]])

# Sumamos la matriz de enmascaramiento
result = np.sum(mask)

print(result)

3


### Lectura recomendada: [Numpy Reference](https://docs.scipy.org/doc/numpy/reference/).